version: '3.7'

services:
  boilerplate_db:
    container_name: boilerplate_db
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
